[package]
name = "limitador-server"
version = "0.5.1"
authors = ["Alex Snaps <asnaps@redhat.com>", "Eguzki Astiz Lezaun <eguzki@redhat.com>", "David Ortiz <z.david.ortiz@gmail.com>"]
license = "Apache-2.0"
keywords = ["rate-limiting", "rate", "limiter", "envoy", "rls"]
categories = ["web-programming"]
description = "Rate limiting service that integrates with Envoy's RLS protocol"
homepage = "https://github.com/kuadrant/limitador"
repository = "https://github.com/kuadrant/limitador"
documentation = "https://docs.rs/limitador"
readme = "README.md"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limitador = { path = "../limitador", features = ['infinispan_storage'] }
tokio = { version = "1", features = ["full"] }
thiserror = "1"
tonic = "0.6"
prost = "0.9"
prost-types = "0.9"
serde_yaml = "0.8"
log = "0.4"
env_logger = "0.9"
url = "2"
actix-web = "4.1"
actix-rt = "2"
paperclip = { version = "0.7", features = ["actix4"] }
serde = { version = "1", features = ["derive"] }
notify = "5.0.0-pre.15"
clap = "3.2.8"
serial_test = "0.7.0"

[build-dependencies]
tonic-build = "0.6"
